import fs from 'node:fs/promises';
const {chromium}=await import(process.env.SCOUTER_PLAYWRIGHT_MODULE||'playwright');
await fs.mkdir('work',{recursive:true});
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true,...(process.env.SCOUTER_BROWSER_EXECUTABLE?{executablePath:process.env.SCOUTER_BROWSER_EXECUTABLE}:{})});
try {
const context=await browser.newContext({viewport:{width:1440,height:1050}});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:4173');await page.waitForSelector('.business-card');assert.equal(await page.locator('.business-card').count(),5);
await page.screenshot({path:'work/scouter-desktop.png',fullPage:true});
await page.getByRole('button',{name:'My service profile',exact:false}).click();await page.locator('[name=name]').fill('Test operator');await page.locator('[name=service-intake]').check();await page.getByRole('button',{name:'Save profile',exact:true}).click();
await page.getByRole('button',{name:'Opportunities',exact:false}).click();await page.getByRole('tab',{name:'Pursuit',exact:true}).click();await page.locator('[name=decision]').selectOption('Pursue');await page.locator('[name=reviewStatus]').selectOption('Reviewed');await page.getByRole('button',{name:'Save pursuit',exact:true}).click();assert.match(await page.locator('#toast').textContent(),/Choose Pursue/);
await page.locator('[name=contactVerified]').check();await page.getByRole('button',{name:'Draft learning message',exact:true}).click();await page.locator('[name=decision]').selectOption('Pursue');await page.locator('[name=contactVerified]').check();await page.locator('[name=reviewStatus]').selectOption('Reviewed');await page.getByRole('button',{name:'Save pursuit',exact:true}).click();assert.equal(await page.locator('[name=reviewStatus]').inputValue(),'Reviewed');
await page.getByRole('tab',{name:'Scope & outcomes',exact:true}).click();assert.equal(await page.locator('#offer-form [name=offer]').isDisabled(),true);
await page.getByRole('tab',{name:'Owner discovery',exact:true}).click();await page.getByRole('button',{name:'+ Record conversation',exact:true}).click();await page.locator('#modal [name=date]').fill('2026-10-06');await page.locator('#modal [name=recipient]').fill('Test owner — simulated QA');await page.locator('#modal [name=ownerWords]').fill('Test statement, not real owner evidence.');await page.locator('#modal [name=ownerVerified]').check();await page.locator('#modal [name=minutes]').fill('12');await page.locator('#modal button[type=submit]').click();assert.equal(await page.locator('blockquote').count(),1);
await page.locator('[name=ownerResult]').fill('Test desired result');await page.locator('[name=problem]').fill('Test problem');await page.getByRole('button',{name:'Save discovery notes',exact:true}).click();await page.getByRole('tab',{name:'Scope & outcomes',exact:true}).click();await page.locator('[name=deliveryService]').selectOption('intake');await page.locator('[name=deliveryConfirmed]').check();await page.getByRole('button',{name:'Save delivery fit',exact:true}).click();assert.equal(await page.locator('#offer-form [name=offer]').isDisabled(),false);
await page.locator('[name=offer]').fill('Test scope');await page.locator('[name=offerPrice]').fill('100');await page.getByRole('button',{name:'Save offer draft',exact:true}).click();
await page.getByRole('button',{name:'+ Log quote / paid work',exact:true}).click();await page.locator('#modal [name=date]').fill('2026-10-07');await page.locator('#modal [name=quote]').fill('100');await page.locator('#modal [name=scope]').fill('Test scope / proposed');await page.locator('#modal [name=reference]').fill('qa-quote-1');await page.locator('#modal button[type=submit]').click();
await page.getByRole('button',{name:'+ Log quote / paid work',exact:true}).click();await page.locator('#modal [name=quote]').fill('100');await page.locator('#modal [name=scope]').fill('Test scope');await page.locator('#modal [name=reference]').fill('qa-quote-1');await page.locator('#modal button[type=submit]').click();assert.match(await page.locator('.form-error').textContent(),/already logged/);await page.getByRole('button',{name:'Cancel',exact:true}).click();
await page.getByRole('button',{name:'Validation review',exact:false}).click();assert.match(await page.locator('.review-notice').textContent(),/OWNER STATEMENTS/);assert.match(await page.locator('.stats').textContent(),/Payments receivedNot recorded/);
await page.reload();await page.getByRole('button',{name:'My service profile',exact:false}).click();assert.equal(await page.locator('[name=name]').inputValue(),'Test operator');
await page.getByRole('button',{name:'Import V1 prospects',exact:true}).click();await page.locator('#modal [name=pipeline]').fill(JSON.stringify([{id:88,name:'QA legacy prospect',hasWebsite:false,status:'Closed'}]));await page.locator('#modal button[type=submit]').click();await page.getByRole('button',{name:'Opportunities',exact:false}).click();assert.equal(await page.locator('.business-card').count(),6);
const backup=JSON.parse(await page.evaluate(()=>localStorage.getItem('scouter.v2.workspace')));await page.getByRole('button',{name:'Restore backup',exact:true}).click();await page.locator('#backup').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await page.locator('#modal button[type=submit]').click();assert.equal(await page.locator('.business-card').count(),6);
await page.locator('#search').fill('no match');assert.equal(await page.locator('.business-card').count(),0);await page.locator('#search').fill('');

await page.getByRole('button',{name:'+ Add business',exact:true}).click();await page.locator('#modal [name=name]').fill('QA intake shop');await page.locator('#modal [name=type]').fill('Test business');await page.locator('#modal [name=method]').selectOption('Random prospecting');await page.locator('#modal [name=website]').fill('https://example.com');await page.locator('#modal [name=question]').fill('What result matters?');await page.locator('#modal button[type=submit]').click();assert.equal(await page.locator('.business-card').count(),7);
await page.getByRole('button',{name:'+ Add evidence',exact:true}).click();await page.locator('#modal [name=text]').fill('QA observation only');await page.locator('#modal [name=url]').fill('https://example.com');await page.locator('#modal button[type=submit]').click();assert.match(await page.locator('.evidence').textContent(),/QA observation/);
await page.getByRole('button',{name:'Start research timer',exact:true}).click();await page.getByRole('button',{name:'Stop & log research',exact:true}).click();await page.locator('#modal [name=date]').fill('2026-10-08');await page.locator('#modal [name=businessId]').selectOption('General');await page.locator('#modal [name=minutes]').fill('15');await page.locator('#modal [name=friction]').fill('QA discarded candidate');await page.locator('#modal button[type=submit]').click();assert.equal(await page.getByRole('button',{name:'Start research timer',exact:true}).count(),1);
await page.getByRole('button',{name:'Activity log',exact:false}).click();assert.match(await page.locator('table').textContent(),/QA discarded candidate/);
const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export activity CSV',exact:true}).click();assert.equal((await downloadPromise).suggestedFilename(),'scouter-activity-log.csv');
await page.getByRole('button',{name:'Validation review',exact:false}).click();assert.match(await page.locator('table').textContent(),/Random prospecting.*15 min/s);await page.locator('[name=conclusion-0]').fill('QA conclusion');await page.getByRole('button',{name:'Save synthesis',exact:true}).click();await page.reload();await page.getByRole('button',{name:'Validation review',exact:false}).click();assert.equal(await page.locator('[name=conclusion-0]').inputValue(),'QA conclusion');
await page.getByRole('button',{name:'Opportunities',exact:false}).click();

const mobile=await context.newPage();await mobile.setViewportSize({width:390,height:844});await mobile.goto('http://127.0.0.1:4173');await mobile.waitForSelector('.business-card');assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);await mobile.screenshot({path:'work/scouter-mobile.png',fullPage:true});
assert.deepEqual(errors,[]);console.log('Browser workflow passed: intake, evidence, profile, review gate, owner discovery, offer gate, quote deduplication, persistence, V1 import, backup restore, timer, baseline, CSV, synthesis, search and mobile layout.');
} finally { await browser.close(); }
